### ISSUE TITLE
Question about the wifi card

### ISSUE THREAD

**Issue by emlynmac** [MirkoCovizzi/thinkpad-p51-hackintosh#4]
Hi, 

Thanks for sharing this awesome info. I've been able to follow and get my P51 up and going except for the wifi...

I assume your P51 didn't come with a BCM94352Z NGFF M.2 - they're usually intel. Which card did you put in, as there's a bunch of incompatible ones I hear?

Thanks!

**Comment by MirkoCovizzi** [comment]
I've replaced the Intel card with the BCM94352Z and it works correctly on
High Sierra, as I specified in the readme. There are a lot of guides on how
to setup the kexts and configurations for the card and on youtube you can
find a handy video on how to replace the wifi module on the P51. I hope
this answer clears your doubts.

**Comment by emlynmac** [comment]
Yeah, the setup and install I’m not bothered about. It was more a question of which exact one you bought so I’d know to get one that works.
