### ISSUE TITLE
Battery status: SUCCESS !

### ISSUE THREAD

**Issue by zealucard** [MirkoCovizzi/thinkpad-p51-hackintosh#6]
Hi, my post is not about an issue but a solution !
I patched my DSDT file with Rehabman tutorial (https://www.tonymacx86.com/threads/guide-patching-laptop-dsdt-ssdts.152573/) and I used battery patch for Lenovo X230i which is working with P51 (from Rehabman repo : https://github.com/RehabMan/Laptop-DSDT-Patch/blob/master/battery/battery_Lenovo-X230i.txt).

And It works ! The percentage is correct and it detects correctly when it's plugged.

![battery_status](https://user-images.githubusercontent.com/22910592/50584491-287e4280-0e70-11e9-942a-9874384e270f.png)

**Comment by MirkoCovizzi** [comment]
I'm glad that the X230 patch works for the P51 too! However, the one I made is 1:1 matched to the P51 without extra strings, changes or side effects. Just keep this in mind.
