### ISSUE TITLE
Syntax error, unexpected PARSEOP_NAME

### ISSUE THREAD

**Issue by lucaschen** [MirkoCovizzi/thinkpad-p51-hackintosh#7]
I'm getting this error when trying to compile my DSDT.dsl.

Has anyone else experienced this issue or have any experience on how to fix it? I can provide more files to explain my situation as needed.

**Comment by Boubak729** [comment]
Hi there, I have the same issues. I've deleted the "One" not working, and marqued as comment with "//" but it always return the error : 6126, syntax error, unexpected PARSEOP_NAME.
I use Catalina on a Thinkpad P51 i7 7700HQ, Quadro 1200, intelHD630 graphic, 24 Gig of RAM,.
Need some help.
Here my files

[DSDT.dsl.zip](https://github.com/MirkoCovizzi/thinkpad-p51-hackintosh/files/4256824/DSDT.dsl.zip)
[DSDT.aml.zip](https://github.com/MirkoCovizzi/thinkpad-p51-hackintosh/files/4256827/DSDT.aml.zip)
![Screen Shot 2020-02-26 at 3 36 00 PM](https://user-images.githubusercontent.com/61504216/75364071-0127d780-58b3-11ea-95fe-7494cf8ed6c4.png)

**Comment by MirkoCovizzi** [comment]
As far as I remember, you have to delete those lines with empty "One" instructions, so, in the image example, lines #221 and #223. Let me know if this fixes your problem.

**Comment by Boubak729** [comment]
Hi, thanks for the answer. someone seems to find out a way and fixed my file for those error.
Now then, my goal at the beginning was to enable the battery status and when I patch it with the DSDT_battery_status_patch.txt content from your EFI folder I end up with some error. I try again with rehabman [bat]Lenovo 230i same error. I correct them all except for one: 31020, 6126, syntax error, unexpected $end and premature End-Of-File.
Again, I am stuck. is it possible to get ride out of this error. I use MaciASL 1.5.7.

[DSDT.zip](https://github.com/MirkoCovizzi/thinkpad-p51-hackintosh/files/4271776/DSDT.zip)

**Comment by MirkoCovizzi** [comment]
I don't remember dealing with that error. Have you tried deleting the extra empty lines at the end of the file?

**Comment by Boubak729** [comment]
Yeah, but the same error  occurs again and again. Even delating some code the error keep jumping.

**Comment by MirkoCovizzi** [comment]
You should consider checking the official tonymacx86 guide for dsdt patching.

https://www.tonymacx86.com/threads/guide-how-to-patch-dsdt-for-working-battery-status.116102/

You will probably find other users that have solved a similar problem in the past.

**Comment by Boubak729** [comment]
I hope so, thanks.

**Comment by Boubak729** [comment]
I finally found a way. It seems like my extracted dsdt have some problems. So I reextract from windows using AIDA64. Now  the dsdt is working fine. Thanks.
