### ISSUE TITLE
thanks so much for your sharing. Do i need to patch it again on my p51 using your configurations? because my battery does not shows its status and my touch pad works only as a mouse

### ISSUE THREAD

**Issue by YiyangHuo** [MirkoCovizzi/thinkpad-p51-hackintosh#9]

**Comment by MirkoCovizzi** [comment]
If you want to properly show battery status, you have to apply the patch [DSDT_battery_status_patch.txt](https://github.com/MirkoCovizzi/thinkpad-p51-hackintosh/blob/master/EFI/CLOVER/ACPI/patched/DSDT_battery_status_patch.txt).

**Comment by YiyangHuo** [comment]
After following the tutorial you have mentioned in battery status, I finally make it works!
